/// Enumerates the possible error values that can be generated by this crate
#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
#[non_exhaustive]
pub enum VSCError {
    /// Unable to detect a version control system
    NoVCS,
    /// Found a type of file that was not allowed. Includes listing of disallowed files found
    NotAllowedFilesFound {
        /// Dirty files found (note this will be empty if dirty files are allowed)
        dirty_files: Vec<String>,
        /// Staged files found (note this will be empty if staged files are allowed)
        staged_files: Vec<String>,
    },
}
